# NumPy 란
- Numpy는 파이썬의 고성능 과학 계산을 위한 라이브러리로, 다차원 배열을 효율적으로 처리합니다. 
- 주로 데이터 분석, 머신러닝, 과학 연구, 엔지니어링 분야에서 활용됩니다.

# NumPy 기본 사용법
### 1. NumPy 라이브러리 가져오기

- NumPy를 사용하기 위해서는 먼저 라이브러리를 import 해야 합니다.

In [ ]:
import numpy as np

### 2. NumPy 배열 생성
- NumPy의 핵심은 다차원 배열(ndarray)입니다. 이 배열은 모두 같은 유형의 데이터를 가지며, 배열의 차원을 표현하는데 사용됩니다.

#### 2-1. 1차원 배열 생성

In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)
# 출력: [1 2 3 4 5]

#### 2-2. 2차원 배열 생성

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)
# 출력:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

#### 2-3. 배열 값의 타입(Type) 확인 또는 지정
- NumPy 배열 값의 타입을 확인하거나 지정할 수 있습니다.

In [ ]:
print(arr_2d.dtype)  # 배열 요소의 데이터 타입 반환
# 출력: int64 (integer 64bit)

arr_2d_uint8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype='uint8')
print(arr_2d_uint8.dtype)  # 배열 요소의 데이터 타입 반환
# 출력: uint8 (unsigned integer 8bit)


### 3. 배열 속성 확인

- NumPy 배열의 다양한 속성을 확인할 수 있습니다.

In [ ]:
print(arr_2d.shape)  # 배열의 형태를 튜플로 반환
# 출력: (3, 3)

print(arr_2d.ndim)   # 배열의 차원 수 반환
# 출력: 2

print(arr_2d.size)   # 배열의 요소 개수 반환
# 출력: 9

print(arr_2d.dtype)  # 배열 요소의 데이터 타입 반환
# 출력: int64

### 4. 같은 형태(Shape) 배열 연산
- 같은 형태(Shape)를 가진 NumPy 배열간 요소별 연산이 가능합니다.

In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print(f"arr1 : {arr1}, arr2 : {arr2}")

# 덧셈
result_add = arr1 + arr2
print('add : ', result_add)
# 출력: [ 6  8 10 12]

# 곱셈
result_mul = arr1 * arr2
print('mul : ', result_mul)
# 출력: [ 5 12 21 32]

# 제곱
result_pow = arr1 ** 2
print('pow : ', result_pow)
# 출력: [ 1  4  9 16]

### 5. 배열과 스칼라(Scala)간 연산
- NumPy 배열과 스칼라(Scala)간 연산이 가능합니다.

In [ ]:
import numpy as np

# 1차원 배열 생성
arr = np.array([1, 2, 3, 4, 5])

# 스칼라 값
scalar = 10

# 배열과 스칼라 덧셈
result_add = arr + scalar

print("배열과 스칼라 덧셈:")
print(result_add)
# 출력: [11 12 13 14 15]

# 배열과 스칼라 뺄셈
result_sub = arr - scalar

print("배열과 스칼라 뺄셈:")
print(result_sub)
# 출력: [-9 -8 -7 -6 -5]

# 배열과 스칼라 곱셈
result_mul = arr * scalar

print("배열과 스칼라 곱셈:")
print(result_mul)
# 출력: [10 20 30 40 50]

# 배열과 스칼라 나눗셈
result_div = arr / scalar

print("배열과 스칼라 나눗셈:")
print(result_div)
# 출력: [0.1 0.2 0.3 0.4 0.5]

# 배열과 스칼라 지수 연산
result_pow = arr ** scalar

print("배열과 스칼라 지수 연산:")
print(result_pow)
# 출력: [    1   100  1000 10000 100000]

# 배열과 스칼라 제곱근
result_sqrt = arr ** 0.5

print("배열 요소의 제곱근:")
print(result_sqrt)
# 출력: [1.         1.41421356 1.73205081 2.         2.23606798]


### 6. 인덱싱과 슬라이싱
- NumPy 배열은 파이썬 리스트와 마찬가지로 인덱싱과 슬라이싱이 가능합니다.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# 인덱싱
print(arr[0])
# 출력: 1

# 슬라이싱
print(arr[1:4])
# 출력: [2 3 4]

In [ ]:
# 2차원 배열에서의 인덱싱과 슬라이싱
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2])  # 1행 2열 요소
# 출력: 6

print(arr_2d[:2, 1:])  # 0~1행, 1~2열 슬라이싱
# 출력:
# [[2 3]
#  [5 6]]

### 7. 배열 생성 시 값 지정
#### 7-1. 고정값 지정

In [ ]:
# 0으로 채워진 배열 생성
zeros_arr = np.zeros((2, 3))
print(zeros_arr)
# 출력:
# [[0. 0. 0.]
#  [0. 0. 0.]]

ones_arr = np.ones((3, 2))
print(ones_arr)
# 출력:
# [[1. 1.]
#  [1. 1.]
#  [1. 1.]]

# 2x3 형태의 2차원 배열을 5로 채움
arr_2d_five = np.full((2, 3), 5)
print(arr_2d_five)
# 출력:
# [[5 5 5]
#  [5 5 5]]

#### 7-2.  랜덤(random)값 지정

In [ ]:
# 1. 정수 난수 생성
# 0에서 9 사이의 정수로 이루어진 1차원 배열
random_ints = np.random.randint(0, 10, size=5)
print(random_ints)
# 출력: [6 0 4 9 6]

# 1에서 20 사이의 정수로 이루어진 2x3 형태의 2차원 배열
random_ints_2d = np.random.randint(1, 21, size=(2, 3))
print(random_ints_2d)
# 출력:
# [[ 5  4  8]
#  [16 10 11]]

# 2. 실수 난수 생성
# 0부터 1 사이의 실수로 이루어진 1차원 배열
random_floats = np.random.rand(5)
print(random_floats)
# 출력: [0.48772369 0.32645563 0.93481944 0.60790383 0.19452714]

# 2x3 형태의 2차원 배열
random_floats_2d = np.random.rand(2, 3)
print(random_floats_2d)
# 출력:
# [[0.42448742 0.75828409 0.83611169]
#  [0.54386223 0.81086794 0.81912079]]

### 8. 배열 형태 변경(reshape)
- reshape 함수는 NumPy 배열의 형태(모양)를 변경할 때 사용됩니다. 즉, 배열의 차원을 바꾸거나, 행과 열의 개수를 조절할 수 있습니다.
#### 8-1. 차원 변경

In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr_1d.reshape(2, 3)

print("2차원 배열:")
print(arr_2d)
# 출력:
# [[1 2 3]
#  [4 5 6]]

In [ ]:
# shape (2, 3, 2)
arr_3d = np.array([[[1, 2],
                    [3, 4],
                    [5, 6]],
                   
                   [[7, 8],
                    [9, 10],
                    [11, 12]]])

arr_2d_reshaped = arr_3d.reshape(3, 4)

print("arr_2d_reshaped shape:", arr_2d_reshaped.shape)
print(arr_2d_reshaped)
# 출력:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

#### 8-2. `-1`을 사용한 자동 계산

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_reshaped = arr.reshape(2, -1, 3)
# arr_reshaped의 shape 항목들의 곱(2 * x * 3) = arr의 shape 항목들의 곱(12)
# => x = 2

print("3차원 배열:")
print(arr_reshaped)
# 출력:
#[[[ 1  2  3]
#  [ 4  5  6]]
# [[ 7  8  9]
#  [10 11 12]]]


In [ ]:
arr.shape

#### 8-3. 다차원 배열을 1차원 배열로 변경(vectorization)

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr_flattened = arr.reshape(-1)
# arr_flattened의 shape 항목들의 곱(x) = arr의 shape 항목들의 곱(3 * 3)
# => x = 9

print("원래 배열:")
print(arr)
# 출력:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

print("1차원 배열:")
print(arr_flattened)
# 출력: [1 2 3 4 5 6 7 8 9]

### 9. 배열 자르기(split)
#### 9-1. `split` 함수
- 배열을 지정된 위치나 축(axis)을 기준으로 여러 개의 하위 배열로 분할

In [ ]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])

# 행을 기준으로 배열을 2개의 부분 배열로 분할
result_2d_row = np.split(arr_2d, 2, axis=0)
print(result_2d_row)
# 출력: [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

# 열을 기준으로 배열을 2개의 부분 배열로 분할
result_2d_col = np.split(arr_2d, 2, axis=1)
print(result_2d_col)
# 출력: [array([[1, 2], [5, 6]]), array([[3, 4], [7, 8]])]


#### 9-2. 배열 스라이싱(slicing)를 이용한 분할(split)

In [ ]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])

# 행을 기준으로 배열을 2개의 부분 배열로 분할
result_2d_row = [ arr_2d[:1, :], arr_2d[1:, :] ]
print(result_2d_row)
# 출력: [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

# 열을 기준으로 배열을 2개의 부분 배열로 분할
result_2d_col = [ arr_2d[:, :2], arr_2d[:, 2:] ]
print(result_2d_col)
# 출력: [array([[1, 2], [5, 6]]), array([[3, 4], [7, 8]])]

### 10. 배열 붙이기(append)
- `append`는 배열에 새로운 요소를 추가한 복사본을 반환합니다. 원본 배열은 변경되지 않습니다.
- 추가하려는 요소의 형태와 배열의 형태(shape)가 일치해야 합니다. 열을 추가할 때는 차원이 맞아야 합니다.

#### 10-1. 1차원 배열에 요소 추가

In [ ]:
arr = np.array([1, 2, 3])

# 요소 4를 배열에 추가
arr_appended = np.append(arr, 4)
print(arr_appended)
# 출력: [1 2 3 4]

# 요소 5, 6, 7을 배열에 추가
arr_appended_multiple = np.append(arr, [5, 6, 7])
print(arr_appended_multiple)
# 출력: [1 2 3 5 6 7]

#### 10-2. 다차원 배열 붙이기

In [ ]:
arr_2d_1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

arr_2d_2 = np.array([[7, 8, 9],
                    [10, 11, 12]])

# 첫번째 차원에 붙이기
appended_row = np.append(arr_2d_1, arr_2d_2, axis=0)
print(appended_row)
# 출력:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]
#  [10 11 12]]

# 두번째 차원에 붙이기
appended_col = np.append(arr_2d_1, arr_2d_2, axis=1)
print(appended_col)
# 출력:
# [[ 1  2  3  7  8  9]
# [ 4  5  6 10 11 12]]

# shape 출력
print('arr_2d_1 arr_2d_2 형태 : ', arr_2d_1.shape, arr_2d_2.shape)
print('appended_row 형태 : ', appended_row.shape)
print('appended_col 형태 : ', appended_col.shape)

### 문제 #1
- dim_1 은 0 ~ 999 1씩 증가하는 1차원 array입니다.
- `reshape` 함수를 사용하여 dim_1을 (? 2 4 5) 형태를 가지는 4차원 array로 변형하도록 to-do 영역을 완성하세요.

In [ ]:
import numpy as np

dim_1 = np.array([ i for i in range(1000) ])
dim_4 = None

# to-do

print(dim_4)

# 예상결과 : 
# ---
# [[[[  0   1   2   3   4]
#    [  5   6   7   8   9]
#    [ 10  11  12  13  14]
#    [ 15  16  17  18  19]]
# 
#   [[ 20  21  22  23  24]
#    [ 25  26  27  28  29]
#    [ 30  31  32  33  34]
#    [ 35  36  37  38  39]]]
#    ...


### 문제 #2
- dim_4는 문제 #1 의 결과값입니다.
- `slicing` 사용하여 dim_4의 마지막 차원(4번째 차원) 첫번째 항목들을 모두 제거하도록 to-do 영역을 완성하세요.

In [ ]:
import numpy as np

dim_1 = np.array([ i for i in range(1000) ])
dim_4 = dim_1.reshape(-1, 2, 4, 5)
removed_4 = None

# to-do

print(removed_4)

# 예상결과 : 
# ---
# [[[[  1   2   3   4]
#    [  6   7   8   9]
#    [ 11  12  13  14]
#    [ 16  17  18  19]]
# 
#   [[ 21  22  23  24]
#    [ 26  27  28  29]
#    [ 31  32  33  34]
#    [ 36  37  38  39]]]
#    ...


## Wrap up
1. **NumPy의 핵심 기능**:

	NumPy는 고성능의 다차원 배열 객체와 이를 다루기 위한 다양한 도구와 함수를 제공합니다. 특히, 다차원 배열(ndarray)의 효율적인 생성과 조작에 초점을 맞춥니다.
2. **배열 연산의 기본**:

	NumPy를 사용하면 큰 데이터 집합에 대해 기본적인 수학 연산을 빠르고 효율적으로 수행할 수 있습니다. 이는 NumPy 배열 간의 연산뿐만 아니라 배열과 스칼라 간의 연산도 포함합니다.
3. **배열의 인덱싱과 슬라이싱**:

	NumPy 배열은 파이썬의 내장 리스트와 유사한 방식으로 인덱싱과 슬라이싱이 가능하며, 이를 통해 배열의 특정 부분을 선택하거나 조작할 수 있습니다.
4. **배열 형태 변경 및 데이터 처리**:

	NumPy는 배열의 형태를 변경하는 다양한 방법을 제공하며, 데이터를 분석하고 처리하는 데 필요한 다양한 함수(예: `reshape`, `split`, `append`)를 포함합니다. 