### numpy 

In [2]:
import numpy as np

In [8]:
#
l = ['abc',2]
a = np.array(l)
print(a)
a.dtype
a.astype('uint8')

['abc' '2']


ValueError: invalid literal for int() with base 10: 'abc'

In [12]:
l = [8,2]
a = np.array(l)
print(a)
print(a.dtype)
a.astype('uint8')

[8 2]
int64


array([8, 2], dtype=uint8)

In [14]:
arr_zero = np.zeros((2,3,4))
arr_zero[1,1,1] = 5
arr_zero

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 5., 0., 0.],
        [0., 0., 0., 0.]]])

In [9]:

noisy_video = np.random.randint(0, 255, size=(2, 3, 4, 5), dtype=np.uint8)
print(noisy_video)

[[[[115  10 248  77 197]
   [ 37  18  43  84  23]
   [ 69 190 116   9 211]
   [151 140   3 207  88]]

  [[179  24  91 131  97]
   [  9 242 130 146  17]
   [ 27 112  23 106 223]
   [166 102 103  91  63]]

  [[ 40  24 157 228  38]
   [ 66 192 142 113 201]
   [144 115 247 152 123]
   [141  50 198 115 245]]]


 [[[181  72  24 243 185]
   [ 36 233 158  47 198]
   [253  19 219 235 248]
   [163 119 217   0 133]]

  [[233  22 223  19 117]
   [ 86 121  66  44 196]
   [102 115  76 169 236]
   [162 155 231 212  21]]

  [[ 74   1 191 202   1]
   [132  47 193  51  30]
   [164 198  47 146 249]
   [  6  37 151 111 159]]]]


In [10]:
# 
vectorized_video = noisy_video.reshape(-1)
print(vectorized_video)

[115  10 248  77 197  37  18  43  84  23  69 190 116   9 211 151 140   3
 207  88 179  24  91 131  97   9 242 130 146  17  27 112  23 106 223 166
 102 103  91  63  40  24 157 228  38  66 192 142 113 201 144 115 247 152
 123 141  50 198 115 245 181  72  24 243 185  36 233 158  47 198 253  19
 219 235 248 163 119 217   0 133 233  22 223  19 117  86 121  66  44 196
 102 115  76 169 236 162 155 231 212  21  74   1 191 202   1 132  47 193
  51  30 164 198  47 146 249   6  37 151 111 159]


In [17]:
reshape_video = noisy_video.reshape([-1,2,10])
print(reshape_video)

[[[115  10 248  77 197  37  18  43  84  23]
  [ 69 190 116   9 211 151 140   3 207  88]]

 [[179  24  91 131  97   9 242 130 146  17]
  [ 27 112  23 106 223 166 102 103  91  63]]

 [[ 40  24 157 228  38  66 192 142 113 201]
  [144 115 247 152 123 141  50 198 115 245]]

 [[181  72  24 243 185  36 233 158  47 198]
  [253  19 219 235 248 163 119 217   0 133]]

 [[233  22 223  19 117  86 121  66  44 196]
  [102 115  76 169 236 162 155 231 212  21]]

 [[ 74   1 191 202   1 132  47 193  51  30]
  [164 198  47 146 249   6  37 151 111 159]]]


In [18]:
reshape_video = noisy_video.reshape([6,-1,10])
print(reshape_video)

[[[115  10 248  77 197  37  18  43  84  23]
  [ 69 190 116   9 211 151 140   3 207  88]]

 [[179  24  91 131  97   9 242 130 146  17]
  [ 27 112  23 106 223 166 102 103  91  63]]

 [[ 40  24 157 228  38  66 192 142 113 201]
  [144 115 247 152 123 141  50 198 115 245]]

 [[181  72  24 243 185  36 233 158  47 198]
  [253  19 219 235 248 163 119 217   0 133]]

 [[233  22 223  19 117  86 121  66  44 196]
  [102 115  76 169 236 162 155 231 212  21]]

 [[ 74   1 191 202   1 132  47 193  51  30]
  [164 198  47 146 249   6  37 151 111 159]]]


In [5]:
deliver_function(print_me)()

I am a deliver.
I was just printed.


'OK'

In [8]:
f = inner_function()
f(print_me)()

I am an inner.
I was just printed.


'OK'

In [9]:
f = closer_function(print_me)
f()

I am a closer.
I was just printed.


In [10]:
def recursive_function(f, i):

    if i==0:
        return
    
    print("Why me?")
    
    f(f, i-1)

recursive_function(recursive_function, 10)

Why me!!
Why me!!
Why me!!
Why me!!
Why me!!
Why me!!
Why me!!
Why me!!
Why me!!
Why me!!
