## 실습.3 numpy 기본

In [1]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


### numpy array 변수에 값 할당

In [1]:
import numpy as np 

l_val = [1, 2, 3, 4, 5, 6, 7, 8, 9]

na = np.array(l_val)

print(na)
print(type(na))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [3]:
l_val = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

na = np.array(l_val)

print(na)
print(na.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


### numpy array 를 list로 변환

In [4]:
l_val_2 = na.tolist()
print(l_val_2)
print(type(l_val_2))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


### list type 과 numpy array type의 차이 알아보기
- '+' : list 에서는 list의 append, numpy에서는 벡터나 행렬에 scala 더하기


In [3]:
new_l_val = l_val + 1
#
# new_l_val = l_val + [1]

TypeError: can only concatenate list (not "int") to list

In [9]:
new_na = na + 1
new_na

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# 왼쪽 operand 다음에 오른쪽 operand 를 append  
new_l_val = l_val + l_val
new_l_val

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1]

In [12]:
new_na = na + na
print(new_na)
new_na.__repr__()

[ 2  4  6  8 10 12 14 16 18]


'array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])'

In [20]:
new_na = na * na
new_na

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [21]:
new_na = na - na
new_na

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

### reshape
    array의 형태(shape) 를 바꿈


In [3]:
list_1 = [1,2,3,4,5,6,7,8,9]
np_arr = np.array(list_1)
reshaped_arr = np_arr.reshape((3,3))

print('값 : ', reshaped_arr)
print('차원(dimension) : ', reshaped_arr.ndim)
print('형태(shape) : ',reshaped_arr.shape)
print('값의 Type : ' ,reshaped_arr.dtype)



값 :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원(dimension) :  2
형태(shape) :  (3, 3)
값의 Type :  int64
