### 사전준비
- parent directory 를 python library path에 추가하기
- mp4 file의 video data를 numpy array 변수에 저장하기

In [1]:
# Parent directory의 .py 파일에 정의된 함수들를 import 하여 사용하기 위해 parent directory 를 python path에 추가합니다.

import sys
import os

current_dir = os.getcwd()
print("Current Directory:", current_dir)

parent_dir = os.path.abspath(os.path.join(current_dir, '..'))
print("Parent Directory:", parent_dir)

sys.path.append(parent_dir)

# System Path 와는 다름
print("System PATH :", os.environ['PATH'])
print("Python Library PATH :", sys.path)

Current Directory: /home/hennry/GitHub/py-lecture-2024/jupyter
Parent Directory: /home/hennry/GitHub/py-lecture-2024
System PATH : /bin:/usr/local/lib/nodejs/node-v18.15.0-linux-x64/bin:/home/hennry/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/lib/nodejs/node-v18.15.0-linux-x64/bin:/home/hennry/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Python Library PATH : ['/home/hennry/GitHub/py-lecture-2024/jupyter', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/home/hennry/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/home/hennry/GitHub/py-lecture-2024']


In [2]:
# ../functions.py 에 미리 정의된 함수들을 import 한다
from functions import video_2_ndarray, ndarray_2_video

# 함수 video_2_ndarray 를 사용하여 ../media/SampleVideo_640x360_5mb.mp4 의 video data를 ndarray 에 저장한다.
video_array, _, _ = video_2_ndarray('../media/SampleVideo_640x360_5mb.mp4')

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enab

In [3]:
# video_array 의 형식과 내용을 확인한다.
print(f'차원(dimension) : {video_array.ndim}')
print(f'형태(shape) : {video_array.shape}')
print('값의 Type : ' ,video_array.dtype)
print('일부 값 확인하기 (frame #0, height #0, width #0~9) : ', video_array[:1,:1,:10,:])

차원(dimension) : 4
형태(shape) : (489, 368, 640, 3)
값의 Type :  uint8
일부 값 확인하기 (frame #0, height #0, width #0~9) :  [[[[3 1 0]
   [3 1 0]
   [3 1 0]
   [3 1 0]
   [3 1 0]
   [3 1 0]
   [3 1 0]
   [3 1 0]
   [3 1 0]
   [3 1 0]]]]


In [ ]:
# numpy를 import 한다
import numpy as np

### 따라 해보기 #1. 이전 실습에서 작성한 code를 함수로 만들기
- 함수 이름 정의
- doc string 작성
- 경우에 따라 test code와 return 구문 작성


In [ ]:
# function 을 정의
def cut_n_append(video_array):
    """
    numpy array type의 video data 를 wight 기준으로 반으로 자르고,
    잘린 오른쪽 array를 왼쪽 array의 밑에 붙이는 함수

    함수 이름 : cut_n_append
    parameters :
        - video_array : 가공 이전의 원본 video array, numpy.ndarray
    return :
        - modified_video_array : 가공된 video array, numpy.ndarray
    """
    # modified_video_array 값 초기화
    modified_video_array = np.array([], dtype=np.uint8)
    print(modified_video_array)

    return modified_video_array

# docstring 출력
print(cut_n_append.__doc__)

# function 실행 test
cut_n_append(video_array)

- 함수 안에 video array 를 변형하는 code 붙이기

In [ ]:
# function 에 code 붙이기
def cut_n_append(video_array):
    """
    numpy array type의 video data 를 wight 기준으로 반으로 자르고,
    잘린 오른쪽 array를 왼쪽 array의 밑에 붙이는 함수

    함수 이름 : cut_n_append
    parameters :
        - video_array : 가공 이전의 원본 video array, numpy.ndarray
    return :
        - modified_video_array : 가공된 video array, numpy.ndarray
    """
    # 삭제된 test code (the 2 lines below)
    #modified_video_array = np.array([], dtype=np.uint8)
    #print(modified_video_array)

    # 여기부터 붙인 code
    # 3번째 차원인 width를 둘로 나누기 위해 너비를 절반으로 나눕니다.
    width_half = video_array.shape[2] // 2

    # 3번째 차원을 둘로 나누어 left_array, right_array를 만듭니다.
    left_array = video_array[:, :, :width_half, :]
    right_array = video_array[:, :, width_half:, :]

    # left_array의 height 차원의 아래쪽에 right_array를 append합니다.
    modified_video_array = np.append(left_array, right_array, axis=1)

    return modified_video_array

- function 실행하고 return 값(변형된 video data)을 변수에 저장

In [ ]:
# function 실행하고 return 값을 변수 new_video_array에 저장
new_video_array = cut_n_append(video_array)

- 변형된 video data를 mp4 파일로 변환

In [ ]:
# new_video_array(변형된 video data)을 mp4 파일로 변환
ndarray_2_video(new_video_array, 'new_video.mp4')

# code 실행 후 생성된 동영상 파일을 실행한다.

### 혼자 해보기 #1. 위 실습에서 만든 video 파일을 변형하여 새로운 video 파일을 만든다.
- video data를 변형하는 function을 작성하기
    - 하고 싶은 작업을 정리해서 genAI에게 질의하자
    - 추천 : 변형한 동영상을 원래대로 되돌리기 해보자

In [ ]:
# function 에 code 붙이기
def cut_n_append2(video_array):
    """
    numpy array type의 video data 를 height 기준으로 반으로 자르고,
    잘린 아래쪽 array를 외쪽 array의 왼쪽에 붙이는 함수

    함수 이름 : cut_n_append2
    parameters :
        - video_array : 가공 이전의 원본 video array, numpy.ndarray
    return :
        - modified_video_array : 가공된 video array, numpy.ndarray
    """
    # 여기부터 붙인 code
    # 3번째 차원인 width를 둘로 나누기 위해 너비를 절반으로 나눕니다.
    height_half = video_array.shape[1] // 2

    # 3번째 차원을 둘로 나누어 upper_array, lower_array를 만듭니다.
    upper_array = video_array[:, :height_half, :, :]
    lower_array = video_array[:, height_half:, :, :]

    # upper_array의 width 차원의 왼쪽에 lower_array를 append합니다.
    modified_video_array = np.append(upper_array, lower_array, axis=2)

    return modified_video_array

- mp4 file의 video data를 numpy array 변수에 저장하기
- function을 실행하고 변경된 numpy array type의 video data를 return 값으로 받기
- return 값을 mp4 파일로 변환

In [ ]:
video_array, _, _ = video_2_ndarray('new_video.mp4')
new_video_array = cut_n_append2(video_array)
ndarray_2_video(new_video_array, 'new2_video.mp4')

# code 실행 후 생성된 동영상 파일을 실행한다.

### 따라 해보기 #2. decorator함수를 사용하여 내가 굳이 알 필요없는 부분을 은닉하자
- decorator함수를 작성한다.

In [ ]:
def modify_video(func):
    def wrapper(video_file, output_file):
        video_array, _, _ = video_2_ndarray(video_file)
        new_video_array = func(video_array)
        ndarray_2_video(new_video_array, output_file)

    return wrapper

- decorator함수를 사용하는 함수를 작성한다.

In [ ]:
@modify_video
def exchange_red_n_blue(video):
    
    new_video = video.copy()
    # R(빨간색) 값과 B(파란색) 값 바꾸기
    new_video[:, :, :, 0], new_video[:, :, :, 1] = video[:, :, :, 2], video[:, :, :, 0]

    return new_video

- decorator함수를 사용하는 함수를 실행한다.
    - parameter는 decorator 함수 안의 closure 함수(여기서는 wrapper) parameter를 사용해야 하는 것에 주의  

In [ ]:
exchange_red_n_blue('../media/SampleVideo_640x360_5mb.mp4', 'exchange_red_n_blue_video.mp4')

# code 실행 후 생성된 동영상 파일을 실행한다.

### 마음대로 해보기 #1. genAI를 사용하여 decorator함수를 만들고 실행해 보자

- (참고) ChatGPT 3.5에 사용한 질의와 답변

In [ ]:
"""
prompt :

다음은 python code 다.

video_array, _, _ = video_2_ndarray('video.mp4')
new_video_array = cut_n_append(video_array)
ndarray_2_video(new_video_array, 'new_video.mp4')
---
위의 code를 아래와 같이 바꾸도록 decorator 함수를 만들어줘

@modify_video
def function1(video_array)
    # 나의 code
    return new_video_array

# 아래 함수가 처음 3 line과 내용이 동일
function1('video.mp4', 'new_video.mp4')
"""

# ChatGPT 3.5 답변
import numpy as np

def modify_video(func):
    def wrapper(video_file, output_file):
        video_array, _, _ = video_2_ndarray(video_file)
        new_video_array = func(video_array)
        ndarray_2_video(new_video_array, output_file)

    return wrapper

@modify_video
def function1(video_array):
    # 나의 code
    return new_video_array

# 실행 예시
function1('video.mp4', 'new_video.mp4')