### 사전준비
    - mp4 file의 video data를 numpy array 변수에 저장하기

In [13]:
# Parent directory의 .py 파일에 정의된 함수들를 import 하여 사용하기 위해 parent directory 를 python path에 추가합니다.

import sys
import os

current_dir = os.getcwd()
print("Current Directory:", current_dir)

parent_dir = os.path.abspath(os.path.join(current_dir, '..'))
print("Parent Directory:", parent_dir)

sys.path.append(parent_dir)

# System Path 와는 다름
print("System PATH :", os.environ['PATH'])
print("Python Library PATH :", sys.path)

Current Directory: /home/hennry/GitHub/py-lecture-2024/jupyter
Parent Directory: /home/hennry/GitHub/py-lecture-2024
System PATH : /bin:/usr/local/lib/nodejs/node-v18.15.0-linux-x64/bin:/home/hennry/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/lib/nodejs/node-v18.15.0-linux-x64/bin:/home/hennry/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Python Library PATH : ['/home/hennry/GitHub/py-lecture-2024/jupyter', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/home/hennry/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/home/hennry/GitHub/py-lecture-2024', '/home/hennry/GitHub/py-lecture-2024']


In [2]:
# ../functions.py 에 미리 정의된 함수들을 import 한다
from functions import video_2_ndarray, ndarray_2_video

# numpy를 import 한다
import numpy as np


In [3]:
# 함수 video_2_ndarray 를 사용하여 ../media/SampleVideo_640x360_5mb.mp4 의 video data를 ndarray 에 저장한다.
video_array, _, _ = video_2_ndarray('../media/SampleVideo_640x360_5mb.mp4')

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enab

In [4]:
# video_array 의 형식과 내용을 확인한다.
print(f'차원(dimension) : {video_array.ndim}')
print(f'형태(shape) : {video_array.shape}')
print('값의 Type : ' ,video_array.dtype)
print('일부 값 (frame #0, height #0, width #0~9) : ', video_array[:1,:1,:10,:])

차원(dimension) : 4
형태(shape) : (759, 368, 640, 3)
값의 Type :  uint8
일부 값 (frame #0, height #0, width #0~9) :  [[[[5 0 0]
   [1 0 0]
   [0 0 0]
   [0 0 0]
   [3 0 4]
   [3 0 4]
   [0 0 0]
   [3 0 0]
   [0 0 0]
   [0 0 0]]]]


### 따라 해보기 #1. 꺼꾸로 play 되는 동영상 만들기

In [5]:
# 1. genAI 에게 아래와 같이 요청한다.

"""
prompt : 
꺼꾸로 play 되는 동영상 만들기
아래와 같은 구조를 가진 numpy array 변수 vedio_array 이 있다

dimension : 4
shape : (frames, height, width, 3(rgb))
data type :  uint8
---
vedio_array 의 frame 들을 역순으로 재배치하여
변수 backwards_video_array 에 저장하는 code를 작성하라
"""

# 2. genAI 의 답변 중 필요한 부분만 잘라 아래 paste 한다.
backwards_video_array = video_array[::-1]

In [6]:
# video_array 의 형식과 내용을 확인한다.
print(f'차원(dimension) : {backwards_video_array.ndim}')
print(f'형태(shape) : {backwards_video_array.shape}')
print('값의 Type : ' ,backwards_video_array.dtype)
print('일부 값 (frame #0, height #0, width #0~9) : ', backwards_video_array[:1,:1,:10,:])

차원(dimension) : 4
형태(shape) : (759, 368, 640, 3)
값의 Type :  uint8
일부 값 (frame #0, height #0, width #0~9) :  [[[[0 0 0]
   [0 0 0]
   [0 0 0]
   [0 0 0]
   [0 0 0]
   [0 0 0]
   [1 1 1]
   [4 4 4]
   [0 0 0]
   [0 0 0]]]]


In [7]:
# 함수 ndarray_2_video 를 사용하여 backwards_video_arr 를 ../media/.mp4 의 video data를 ndarray 에 저장한다.
ndarray_2_video(backwards_video_array, 'backwards_video.mp4')

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enab

### 혼자 해보기 #1. 동영상의 색상을 반전시켜라
    - genAI 에게 질의할 prompt 를 작성한다.
    - genAI 의 답변을 참조하여 code를 완성한다

In [9]:
# 동영상의 색상을 반전시키는 code
reversed_video_array = 255 - video_array
# video data 로 mp4 파일 생성
ndarray_2_video(reversed_video_array, 'reversed_video.mp4')


ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enab

### 따라 해보기 #2. 하나의 복잡한 문제를 여러 개의 서브 문제들로 분할 후 각각을 해결해서 종합(Least to Most 방식)
    - 문제를 분할 한다.
    - 분할된 문제를 하나씩 genAI 에게 질의한다.
        - 답변이 정확해진 후 genAI 에게 다음 질의을 한다.
    - genAI 의 전체 답변을 참조하여 code를 완성한다

In [10]:
# 여기에 code 를 작성
"""
질의 #1)
prompt :
vedio_array의 3번째 차원 width를 둘로 나누어 두개의 numpy ndarray value left_array, right_array 를 만드는 code를 작성하라

질의 #2)
prompt :
left_array 의 height 차원의 아래쪽에 right_array 를 append 하도록 code를 작성하라
"""
# 3번째 차원인 width를 둘로 나누기 위해 너비를 절반으로 나눕니다.
width_half = video_array.shape[2] // 2

# 3번째 차원을 둘로 나누어 left_array, right_array를 만듭니다.
left_array = video_array[:, :, :width_half, :]
right_array = video_array[:, :, width_half:, :]

# left_array의 height 차원의 아래쪽에 right_array를 append합니다.
combined_array = np.append(left_array, right_array, axis=1)

차원(dimension) : 4
형태(shape) : (759, 736, 320, 3)
값의 Type :  uint8
일부 값 (frame #0, height #0, width #0~9) :  [[[[5 0 0]
   [1 0 0]
   [0 0 0]
   [0 0 0]
   [3 0 4]
   [3 0 4]
   [0 0 0]
   [3 0 0]
   [0 0 0]
   [0 0 0]]]]


In [11]:
# video_array 의 형식과 내용을 확인한다.
print(f'차원(dimension) : {combined_array.ndim}')
print(f'형태(shape) : {combined_array.shape}')
print('값의 Type : ' ,combined_array.dtype)
print('일부 값 (frame #0, height #0, width #0~9) : ', combined_array[:1,:1,:10,:])

차원(dimension) : 4
형태(shape) : (759, 736, 320, 3)
값의 Type :  uint8
일부 값 (frame #0, height #0, width #0~9) :  [[[[5 0 0]
   [1 0 0]
   [0 0 0]
   [0 0 0]
   [3 0 4]
   [3 0 4]
   [0 0 0]
   [3 0 0]
   [0 0 0]
   [0 0 0]]]]


In [12]:
# video data 로 mp4 파일 생성
ndarray_2_video(combined_array, 'cut_n_combined_video.mp4')

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enab

### 마음대로 해보기 #1. 원본을 가공하여 새로운 동영상을 만들자