### 사전준비
    - mp4 file의 video data를 numpy array 변수에 저장하기

In [1]:
# Parent directory의 .py 파일에 정의된 함수들를 import 하여 사용하기 위해 parent directory 를 python path에 추가합니다.

import sys
import os

current_dir = os.getcwd()
print("Current Directory:", current_dir)

parent_dir = os.path.abspath(os.path.join(current_dir, '..'))
print("Parent Directory:", parent_dir)

sys.path.append(parent_dir)

# System Path 와는 다름
print("System PATH :", os.environ['PATH'])
print("Python Library PATH :", sys.path)

Current Directory: /home/hennry/GitHub/py-lecture-2024/jupyter
Parent Directory: /home/hennry/GitHub/py-lecture-2024
System PATH : /bin:/usr/local/lib/nodejs/node-v18.15.0-linux-x64/bin:/home/hennry/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/lib/nodejs/node-v18.15.0-linux-x64/bin:/home/hennry/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Python Library PATH : ['/home/hennry/GitHub/py-lecture-2024/jupyter', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/home/hennry/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/home/hennry/GitHub/py-lecture-2024']


In [3]:
# ../functions.py 에 미리 정의된 함수들을 import 한다
from functions import video_2_ndarray, ndarray_2_video

# numpy를 import 한다
import numpy as np

In [4]:
# 함수 video_2_ndarray 를 사용하여 ../media/SampleVideo_640x360_5mb.mp4 의 video data를 ndarray 에 저장한다.
video_array, _, _ = video_2_ndarray('../media/SampleVideo_640x360_5mb.mp4')

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enab

In [5]:
# video_array 의 형식과 내용을 확인한다.
print(f'차원(dimension) : {video_array.ndim}')
print(f'형태(shape) : {video_array.shape}')
print('값의 Type : ' ,video_array.dtype)
print('일부 값 (frame #0, height #0, width #0~9) : ', video_array[:1,:1,:10,:])

차원(dimension) : 4
형태(shape) : (759, 368, 640, 3)
값의 Type :  uint8
일부 값 (frame #0, height #0, width #0~9) :  [[[[5 0 0]
   [1 0 0]
   [0 0 0]
   [0 0 0]
   [3 0 4]
   [3 0 4]
   [0 0 0]
   [3 0 0]
   [0 0 0]
   [0 0 0]]]]


### 따라 해보기 #1. 이전 실습에서 작성한 video array 편집 code를 함수로 만들기

In [18]:
# function 을 정의
def cut_n_append(video_array):
    """
    numpy array type의 video data 를 wight 기준으로 반으로 자르고,
    잘린 오른쪽 array를 왼쪽 array의 밑에 붙이는 함수

    함수 이름 : cut_n_append
    parameters :
        - video_array : 가공 이전의 원본 video array, numpy.ndarray
    return :
        - modified_video_array : 가공된 video array, numpy.ndarray
    """
    # modified_video_array 값 초기화
    modified_video_array = np.array([], dtype=np.uint8)
    print(modified_video_array)

    return modified_video_array

# docstring 출력
print(cut_n_append.__doc__)

# function 실행 test
cut_n_append(video_array)


    numpy array type의 video data 를 wight 기준으로 반으로 자르고,
    잘린 오른쪽 array를 왼쪽 array의 밑에 붙이는 함수

    함수 이름 : cut_n_append
    parameters :
        - video_array : 가공 이전의 원본 video array, numpy.ndarray
    return :
        - modified_video_array : 가공된 video array, numpy.ndarray
    
[]


array([], dtype=float64)

In [19]:
# function 에 code 붙이기
def cut_n_append(video_array):
    """
    numpy array type의 video data 를 wight 기준으로 반으로 자르고,
    잘린 오른쪽 array를 왼쪽 array의 밑에 붙이는 함수

    함수 이름 : cut_n_append
    parameters :
        - video_array : 가공 이전의 원본 video array, numpy.ndarray
    return :
        - modified_video_array : 가공된 video array, numpy.ndarray
    """
    # 여기부터 붙인 code
    # 3번째 차원인 width를 둘로 나누기 위해 너비를 절반으로 나눕니다.
    width_half = video_array.shape[2] // 2

    # 3번째 차원을 둘로 나누어 left_array, right_array를 만듭니다.
    left_array = video_array[:, :, :width_half, :]
    right_array = video_array[:, :, width_half:, :]

    # left_array의 height 차원의 아래쪽에 right_array를 append합니다.
    modified_video_array = np.append(left_array, right_array, axis=1)

    return modified_video_array

In [20]:
# function 실행
new_video_array = cut_n_append(video_array)

In [21]:
# video data 로 mp4 파일 생성
ndarray_2_video(new_video_array, 'new_video.mp4')

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enab